name: 构建和部署

on:
  push:
    branches: [ main ]  # 根据你的主分支名称调整，可能是master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - uses: actions/checkout@v4

      # 设置Node.js环境
      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 安装依赖
      - name: 安装依赖
        run: npm ci

      # 构建项目
      - name: 构建
        run: npm run build

      # 备份服务器上的现有 dist 目录
      - name: 备份现有dist目录
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 139.224.59.6
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            timestamp=$(date +%Y%m%d_%H%M%S)
            if [ -d "/www/wwwroot/tyle.hxxd.tv/dist" ]; then
              cp -r /www/wwwroot/tyle.hxxd.tv/dist /www/wwwroot/tyle.hxxd.tv/dist_backup_$timestamp
              rm -rf /www/wwwroot/tyle.hxxd.tv/dist
              echo "已备份 dist 目录到 dist_backup_$timestamp 并删除原目录"
            else
              echo "没有找到 dist 目录，跳过备份"
            fi

      # 使用 SCP Action 上传文件
      - name: 上传文件到服务器
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 139.224.59.6
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "dist/"
          target: "/www/wwwroot/tyle.hxxd.tv/"
          strip_components: 0  # 保留dist目录
          rm: false  # 不删除目标目录，因为我们已经手动处理了

      # 使用 SSH Action 设置权限
      - name: 设置文件权限
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 139.224.59.6
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            chmod -R 755 /www/wwwroot/tyle.hxxd.tv/dist
